// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScuolaMVC_RepoStudCorsi.Data;

#nullable disable

namespace ScuolaMVC.Migrations
{
    [DbContext(typeof(ScuolaContext))]
    [Migration("20251208175701_AggiungiModelloCorso")]
    partial class AggiungiModelloCorso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScuolaMVC_RepoStudCorsi.Models.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("ScuolaMVC_RepoStudCorsi.Models.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("ScuolaMVC_RepoStudCorsi.Models.StudenteCorso", b =>
                {
                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.HasKey("StudenteId", "CorsoId");

                    b.HasIndex("CorsoId");

                    b.ToTable("StudentiCorsi");
                });

            modelBuilder.Entity("ScuolaMVC_RepoStudCorsi.Models.StudenteCorso", b =>
                {
                    b.HasOne("ScuolaMVC_RepoStudCorsi.Models.Corso", "Corso")
                        .WithMany("Studenti")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScuolaMVC_RepoStudCorsi.Models.Studente", "Studente")
                        .WithMany("Corsi")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("ScuolaMVC_RepoStudCorsi.Models.Corso", b =>
                {
                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("ScuolaMVC_RepoStudCorsi.Models.Studente", b =>
                {
                    b.Navigation("Corsi");
                });
#pragma warning restore 612, 618
        }
    }
}
